### ISSUE TITLE
Memory settings configuration

### ISSUE THREAD

**Issue by geraldpereira** [OctoPerf/kraken#46]
Handle environment variables for memory and CPU requests/limits:

- Docker: https://docs.docker.com/compose/compose-file/#resources
- Kubernetes: https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/#specify-a-memory-request-and-a-memory-limit

Set the Xmx accordingly https://developers.redhat.com/blog/2017/03/14/java-inside-docker/

Configuration in runtime's application.yml file for default values:

``` yaml
resources-allocation:
  cpu: 
    request: 0.5
    limit: 1.0 (optional)
  memory:
    request: 512M
    limit: 1G (optional)
```
